### ISSUE TITLE
Ender dragon spawning Dragon egg

### ISSUE THREAD

**Issue by Olthoo** [BONNePlayground/DragonFights#12]
### Description
I don't know if it's a bug or a feature but only the first dragon fight of the server spawn an egg and give 70lvl of exp. I would like that the first dragon of every island is treated as such, so every team can get an egg.

**Comment by BONNe** [comment]
Hmmm, on my test server, it spawns an egg on each island after the first battle.
![both-eggs](https://user-images.githubusercontent.com/1344358/210803912-904aa793-be0e-4a6c-a2ab-0f20d6a9b48a.png)

In the image you can see that both have dragon eggs, the same server, and islands are not in the same location.

**Comment by BONNe** [comment]
Maybe you have some sort of plugin that blocks dragon-egg duplication? May be that plugin blocks all dragon eggs when one is spawned?

I am guessing because the egg should have been spawned after the first battle on each island.

**Comment by Olthoo** [comment]
If I reset the end world & dragon fight database I get a new egg, I tested with almost empty server
![image](https://user-images.githubusercontent.com/86952294/210884593-c3026644-9407-45c6-b107-33cd9adde5f8.png)
everything in the purpur config _looks_ unchanged. I can give you access to the test server if you can help me troubleshoot ^^'

**Comment by Olthoo** [comment]
don't know how but now it works, it might have been an issue with islands created before the addon was added
