### ISSUE TITLE
Infinite teleportation

### ISSUE THREAD

**Issue by daniel-skopek** [BONNePlayground/DragonFights#16]
#### Describe the bug

If I kill a dragon, the end portal spawns and if I jump into the portal, it teleports me back to the End portal and so on. So I'm stuck in an endless teleport through the End Portal. It will only happen to one player. (We tested it with two)

#### Steps to reproduce the behavior

1. Spawn enderdragon
2. Destroy the towers
3. Kill the dragon
4. Jump into the End Portal
5. You will be stuck

#### Expected behavior

After jumping into the End portal, it should teleport me back to my OneBlock island.

##### BentoBox Version (Mandatory)

```
I'm running on PAPER Invalid.
Loaded game worlds:
oneblock_world (OneBlock): World, Nether*, End
loaded add-ons:
AOneBlock 1.11.0 (ENABLED)
Biomes 2.1.0 (ENABLED)
Challenges 1.1.0 (ENABLED)
Chat 1.1.4 (ENABLED)
DragonFights 1.4.4 (ENABLED)
Level 2.9.0 (ENABLED)
Limits 1.19.0 (ENABLED)
Warps 1.12.0 (ENABLED)
```

#### Plugins (Optional)

```
Plugins (4): BentoBox, LuckPerms, Vault, ViaVersion
```

**Comment by BONNe** [comment]
Teleportation is managed by BentoBox. Please open a ticket in [BentoBox ](https://github.com/BentoBoxWorld/BentoBox) repo.
