### ISSUE TITLE
Dragon dont spawn, spaming errors, 1.20.4

### ISSUE THREAD

**Issue by SirvydasS** [BONNePlayground/DragonFights#30]
#### Steps to reproduce the behavior

When trying spawn dragon (putting 4 crystals) obsdian toweers spawns, but not the dragon and getting erros. (on first try somehow dragon spawns, but for the second time he didn't)

#### Expected behavior

Dragon spawns and no errors.

#### Screenshots and videos (Optional)

https://pastebin.com/tqh6K9wq

##### BentoBox Version (Mandatory)

![image](https://github.com/BONNePlayground/DragonFights/assets/8950371/b9b511e5-a686-490a-99dd-242b1422b329)

**Comment by BONNe** [comment]
There are some issues with loading addon on 1.20.1/2 but on 1.20.4 there should not be issues with 1.8.1 release.

**Comment by SirvydasS** [comment]
No problems when downloaded from here: https://github.com/BONNePlayground/DragonFights/releases
